/// Flutter icons PokemonIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///

///
///
///
import 'package:flutter/widgets.dart';
import 'package:pokemon_gotta_catch_them_all/app/features/shared/utils/pokemon_types.dart';

class PokemonIcons {
  PokemonIcons._();

  static const _kFontFam = 'PokemonIcons';
  static const String? _kFontPkg = null;

  static const IconData attackIcon =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData citiesIcon =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cityIcon =
      IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData defenseIcon =
      IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lifeIcon =
      IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pokemonIcon =
      IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData regionIcon =
      IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData speedIcon =
      IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
